// Product data for different sections
export const hotSellingProducts = [
  {
    id: 'hs1',
    name: 'Dentaltech Korean Implant Compatible Healing Abutment',
    description: 'Precision titanium abutments designed to guide gum...',
    currentPrice: 120,
    originalPrice: undefined,
    rating: 4,
    reviewCount: 15,
    image: '/products/abutment1.jpg',
    inStock: true,
    options: 6,
    brand: 'Dentaltech'
  },
  {
    id: 'hs2', 
    name: 'Dentaltech Nobel Implant Compatible Lab Analog',
    description: 'Precisely engineered analogs ensuring accurate prosthetic...',
    currentPrice: 200,
    originalPrice: undefined,
    rating: 5,
    reviewCount: 23,
    image: '/products/analog1.jpg',
    inStock: true,
    options: 6,
    brand: 'Dentaltech'
  },
  {
    id: 'hs3',
    name: 'Dentaltech Nobel Implant Compatible Close Tray...',
    description: 'Precision-fit close tray impression copings...',
    currentPrice: 450,
    originalPrice: undefined,
    rating: 4,
    reviewCount: 18,
    image: '/products/tray1.jpg',
    inStock: true,
    options: 3,
    brand: 'Dentaltech'
  },
  {
    id: 'hs4',
    name: 'DentalTech Korean Implant Compatible Close Tray...',
    description: 'Precision-engineered titanium copings for accurate Korean...',
    currentPrice: 300,
    originalPrice: undefined,
    rating: 4,
    reviewCount: 12,
    image: '/products/tray2.jpg',
    inStock: true,
    options: 2,
    brand: 'DentalTech'
  },
  {
    id: 'hs5',
    name: 'Dentaltech Straumann BLX Implant Compatible Close...',
    description: 'Precision titanium coping ensures accurate closed tray...',
    currentPrice: 1500,
    originalPrice: 2490,
    rating: 4,
    reviewCount: 60,
    discount: 40,
    image: '/products/straumann.jpg',
    inStock: true,
    options: 3,
    brand: 'Dentaltech'
  },
  {
    id: 'hs6',
    name: 'Dentaltech Nobel RP Implant Compatible Premil Abutment',
    description: 'High-precision titanium blank for CAD/CAM milling of...',
    currentPrice: 600,
    originalPrice: 1190,
    rating: 5,
    reviewCount: 24,
    discount: 50,
    badge: 'Only 4 Left',
    image: '/products/premil.jpg',
    inStock: true,
    options: 3,
    brand: 'Dentaltech'
  }
];

export const medidenProducts = [
  {
    id: 'md1',
    name: 'Mediden Osstem TS Mini Compatible Titanium...',
    description: 'Osstem TS mini titanium Ti-base abutment (4mm)...',
    currentPrice: 192,
    originalPrice: 380,
    rating: 4,
    reviewCount: 10,
    discount: 49,
    image: '/products/mediden1.jpg',
    inStock: true,
    options: 4,
    brand: 'Mediden'
  },
  {
    id: 'md2',
    name: 'Mediden Nobel Biocare Active NP Compatible 3D Digital...',
    description: 'Mediden 3D Digital Implant Analog designed for Nobel...',
    currentPrice: 114,
    originalPrice: 2800,
    rating: 4,
    reviewCount: 10,
    discount: 96,
    badge: 'Only 2 Left',
    image: '/products/mediden2.jpg',
    inStock: true,
    options: 4,
    brand: 'Mediden'
  },
  {
    id: 'md3',
    name: 'Mediden Nobel Biocare Active Compatible Model Scanbody...',
    description: 'Mediden 3-47 Perfecta tailored for Nobel Biocare RP...',
    currentPrice: 321,
    originalPrice: 800,
    rating: 4,
    reviewCount: 35,
    discount: 60,
    image: '/products/mediden3.jpg',
    inStock: true,
    options: 4,
    brand: 'Mediden'
  },
  {
    id: 'md4',
    name: 'Mediden Israeli Compatible Titanium Ti-base Abutment...',
    description: 'Mediden TS Ti-base Israeli compatible Titanium Ti-base...',
    currentPrice: 1125,
    originalPrice: 2300,
    rating: 4,
    reviewCount: 10,
    discount: 51,
    image: '/products/mediden4.jpg',
    inStock: true,
    options: 4,
    brand: 'Mediden'
  },
  {
    id: 'md5',
    name: 'Mediden Nobel Active RP Compatible Titanium...',
    description: 'Mediden TS 3-47 screw. Titanium abutment for Nobel...',
    currentPrice: 192,
    originalPrice: 510,
    rating: 4,
    reviewCount: 2,
    discount: 62,
    image: '/products/mediden5.jpg',
    inStock: true,
    options: 3,
    brand: 'Mediden'
  },
  {
    id: 'md6',
    name: 'Mediden Nobel Active NP Compatible Titanium...',
    description: 'Mediden TS 5-48 screw. Titanium abutment for Nobel...',
    currentPrice: 192,
    originalPrice: 510,
    rating: 4,
    reviewCount: 2,
    discount: 62,
    image: '/products/mediden6.jpg',
    inStock: true,
    options: 3,
    brand: 'Mediden'
  }
];

export const superendoProducts = [
  {
    id: 'se1',
    name: 'SuperEndo Disposable Irrigation Needles - Pack of 25',
    description: 'High-quality, single-use irrigation needles designed for...',
    currentPrice: 234,
    originalPrice: undefined,
    rating: 4,
    reviewCount: 6,
    image: '/products/superendo1.jpg',
    inStock: true,
    options: 4,
    brand: 'SuperEndo'
  },
  {
    id: 'se2',
    name: 'SuperEndo Gold-Flex Rotary Files (Pack of 6)',
    description: 'Heat Activated Gold rotary file for Root Canal...',
    currentPrice: 839,
    originalPrice: undefined,
    rating: 4,
    reviewCount: 51,
    image: '/products/superendo2.jpg',
    inStock: true,
    options: 14,
    brand: 'SuperEndo'
  },
  {
    id: 'se3',
    name: 'SuperEndo Sonic Flush Endo Irrigator (3D Tips Free)',
    description: 'Endodontic irrigator with sonic energy. LED light, and...',
    currentPrice: 8897,
    originalPrice: undefined,
    rating: 5,
    reviewCount: 1,
    image: '/products/superendo3.jpg',
    inStock: true,
    options: 4,
    brand: 'SuperEndo'
  },
  {
    id: 'se4',
    name: 'SuperEndo Crown Preparation Bur Kit',
    description: 'Diamond FG burs for crown preparation',
    currentPrice: 550,
    originalPrice: 1800,
    rating: 4,
    reviewCount: 9,
    discount: 69,
    image: '/products/superendo4.jpg',
    inStock: true,
    options: 2,
    brand: 'SuperEndo'
  },
  {
    id: 'se5',
    name: 'SuperEndo Dental Buchanan Hand Pluggers',
    description: 'Root Canal Vertical Filling And Condensation Endodontic...',
    currentPrice: 891,
    originalPrice: undefined,
    rating: 4,
    reviewCount: 4,
    image: '/products/superendo5.jpg',
    inStock: true,
    options: 1,
    brand: 'SuperEndo'
  },
  {
    id: 'se6',
    name: 'SuperEndo ProCut Gutta Percha Cutter',
    description: 'Wireless gutta-percha cutter ensures rapid heating...',
    currentPrice: 1687,
    originalPrice: undefined,
    rating: 1,
    reviewCount: 1,
    image: '/products/superendo6.jpg',
    inStock: true,
    options: 2,
    brand: 'SuperEndo'
  }
];

export const waldentAlchemProducts = [
  {
    id: 'wa1',
    name: 'Waldent Caries Detector',
    description: 'Efficient caries disclosing agent for conservative...',
    currentPrice: 113,
    originalPrice: 378,
    rating: 4,
    reviewCount: 3,
    discount: 70,
    image: '/products/waldent1.jpg',
    inStock: true,
    options: 2,
    brand: 'Waldent'
  },
  {
    id: 'wa2',
    name: 'Waldent RCTpex Root Canal Filling Material (Radiopaque)',
    description: 'Calcium Hydroxide paste with iodoform',
    currentPrice: 464,
    originalPrice: 800,
    rating: 4,
    reviewCount: 3,
    discount: 42,
    image: '/products/waldent2.jpg',
    inStock: true,
    options: 2,
    brand: 'Waldent'
  },
  {
    id: 'wa3',
    name: 'Waldent Zinc Oxide Powder',
    description: 'Zinc oxide powder for temporary dental dressings',
    currentPrice: 80,
    originalPrice: 288,
    rating: 4,
    reviewCount: 6,
    discount: 72,
    image: '/products/waldent3.jpg',
    inStock: true,
    options: 1,
    brand: 'Waldent'
  },
  {
    id: 'wa4',
    name: 'Waldent FlexiPrint Alginate Powder Impression Material',
    description: 'Chromatic, dust free, high precision alginate impressio...',
    currentPrice: 295,
    originalPrice: 880,
    rating: 4,
    reviewCount: 17,
    discount: 66,
    image: '/products/waldent4.jpg',
    inStock: true,
    options: 5,
    brand: 'Waldent'
  },
  {
    id: 'wa5',
    name: 'Waldent Camphor Mono Chlorophenol (CMCP)',
    description: 'Intermediate disinfectant solution for root canals...',
    currentPrice: 113,
    originalPrice: 480,
    rating: 5,
    reviewCount: 6,
    discount: 76,
    image: '/products/waldent5.jpg',
    inStock: true,
    options: 2,
    brand: 'Waldent'
  },
  {
    id: 'wa6',
    name: 'Waldent Gum Paint Based Gingival...',
    description: 'Light cured zinc phosphate paste for....',
    currentPrice: 277,
    originalPrice: 484,
    rating: 4,
    reviewCount: 9,
    discount: 43,
    image: '/products/waldent6.jpg',
    inStock: true,
    options: 4,
    brand: 'Waldent'
  }
];

export const etDentalProducts = [
  {
    id: 'et1',
    name: 'ET Dental VisiSafe Intraoral Camera Sheath (100pcs/Box)',
    description: 'Disposable, durable sleeves that protect intraoral...',
    currentPrice: 890,
    originalPrice: 1800,
    rating: 5,
    reviewCount: 26,
    discount: 51,
    image: '/products/et1.jpg',
    inStock: true,
    options: 2,
    brand: 'ET Dental'
  },
  {
    id: 'et2',
    name: 'ET Dental Disposable Instrument Kit',
    description: 'Disposable diagnostic instrument kit',
    currentPrice: 33,
    originalPrice: undefined,
    rating: 5,
    reviewCount: 1,
    image: '/products/et2.jpg',
    inStock: true,
    options: 2,
    brand: 'ET Dental'
  },
  {
    id: 'et3',
    name: 'ET Dental Rubber Mixing Bowls',
    description: 'Flexible, Durable Rubber Mixing Bowls Ideal for smooth and...',
    currentPrice: 100,
    originalPrice: undefined,
    rating: 4,
    reviewCount: 6,
    image: '/products/et3.jpg',
    inStock: true,
    options: 4,
    brand: 'ET Dental'
  },
  {
    id: 'et4',
    name: 'ET Dental Relax Mouth Mirror (Pack of 10)',
    description: 'High quality clear vision mouth mirror with handle',
    currentPrice: 647,
    originalPrice: undefined,
    rating: 4,
    reviewCount: 7,
    image: '/products/et4.jpg',
    inStock: true,
    options: 3,
    brand: 'ET Dental'
  },
  {
    id: 'et5',
    name: 'ET Dental Dispensing Gun',
    description: 'Dispensing gun used for crown & bridge material (1:4) and...',
    currentPrice: 525,
    originalPrice: undefined,
    rating: 4,
    reviewCount: 2,
    image: '/products/et5.jpg',
    inStock: true,
    options: 1,
    brand: 'ET Dental'
  },
  {
    id: 'et6',
    name: 'ET Dental Chair Cover (Washable)',
    description: 'Washable dental chair & dentist stool protective cover...',
    currentPrice: 795,
    originalPrice: undefined,
    rating: 5,
    reviewCount: 5,
    image: '/products/et6.jpg',
    inStock: true,
    options: 4,
    brand: 'ET Dental'
  }
];

export const mostSearchedProducts = [
  {
    id: 'ms1',
    name: 'UU Ortho TriAlign Pro Multi-Layer Face Align Sheets for...',
    description: 'High-performance multi-layer thermoplastic sheets for...',
    currentPrice: 1592,
    originalPrice: undefined,
    rating: 4,
    reviewCount: 1,
    image: '/products/most1.jpg',
    inStock: true,
    options: 2,
    brand: 'UU Ortho'
  },
  {
    id: 'ms2',
    name: 'Waldent NanoFill Zirconium Restorative Composite A3.5',
    description: 'Zirconium-enhanced nanohybrid composite for...',
    currentPrice: 422,
    originalPrice: 1050,
    rating: 4,
    reviewCount: 20,
    discount: 60,
    image: '/products/most2.jpg',
    inStock: true,
    options: 2,
    brand: 'Waldent'
  },
  {
    id: 'ms3',
    name: 'Elegoo Standard 2.0 3D Printing Photopolymer Resin',
    description: 'Premium resin for accurate, smooth, fast-curing LCD 3D...',
    currentPrice: 1499,
    originalPrice: undefined,
    rating: 5,
    reviewCount: 1,
    image: '/products/most3.jpg',
    inStock: true,
    options: 4,
    brand: 'Elegoo'
  },
  {
    id: 'ms4',
    name: 'Dentsply Spectrum Composite Kit',
    description: 'Universal Microhybrid Composite Restorative kit',
    currentPrice: 3214,
    originalPrice: 6620,
    rating: 4,
    reviewCount: 1,
    discount: 51,
    image: '/products/most4.jpg',
    inStock: true,
    options: 2,
    brand: 'Dentsply'
  },
  {
    id: 'ms5',
    name: 'OrthoMetric Advanced Series Metal Bracket Kit 022 -..',
    description: 'Durable metal bracket kit designed for efficient...',
    currentPrice: 553,
    originalPrice: undefined,
    rating: 5,
    reviewCount: 1,
    image: '/products/most5.jpg',
    inStock: true,
    options: 4,
    brand: 'OrthoMetric'
  },
  {
    id: 'ms6',
    name: 'Noclar Varioflink N Intro Pack',
    description: 'Dual-cure, aesthetic luting composite for...',
    currentPrice: 7644,
    originalPrice: 12235,
    rating: 4,
    reviewCount: 75,
    discount: 38,
    badge: 'Only 5 Left',
    image: '/products/most6.jpg',
    inStock: true,
    options: 2,
    brand: 'Noclar'
  }
];